#!/bin/bash

dir=`date +"%Y/%m"`
[ -d $dir ] || mkdir -p $dir

file=`date +"%d.md"`
path="$dir/$file"

if [ -e $path ]; then
  cd $dir; vim $file
else
  > $path
  date >> $path
  echo '===' >> $path
  echo >> $path
  cd $dir; vim $file
fi
