refresh:
	cp ~/.i3/config ./i3config.txt
	cp ~/Dropbox/cympfh/sh/bashrc.txt .
	cp ~/Dropbox/cympfh/i3status.js .
	cp ~/.inputrc .
	cp ~/Dropbox/cympfh/screenrc.txt .
	cp ~/Dropbox/cympfh/vim/vimrc.vim ./vimrc.txt
