refresh:
	cp ~/.i3/config ./i3.config.txt
	cp ~/Dropbox/cympfh/sh/bashrc.txt .
	cp ~/Dropbox/cympfh/i3status.js .
	cp ~/.inputrc .
	cp ~/Dropbox/cympfh/screen/rc.txt ./screenrc.txt
	cp ~/Dropbox/cympfh/vim/rc.vim ./vimrc.txt
	cp ~/.config/peco/config.json ./peco.config.json
