#!/bin/sh

URL=$1
ID=`echo $URL | sed -e 's/^.*\///' -e 's/&.*$//' -e 's/^.*=//'`

TITLE=` \
curl -s https://www.youtube.com/watch?v=${ID} \
  | grep '<title>' \
  | sed -e 's/^.*<title>//' -e 's/ - YouTube.*$//' \
        -e 's/&amp;/\&/g' -e 's/&gt;/>/g' -e 's/&lt;/</g' -e "s/&apos;/apos/g"`

echo $ID $TITLE

