#!/bin/bash

# remove the id of removed movies
# from a playlist file

[ $# -ne 1 ] && echo "./% [playlist]" && exit 0

> $1.tmp

cx=0

while read ln; do
  id=${ln%% *}
  if [ "_${id}" = "_#" ]
  then
    echo $ln >> $1.tmp
  elif [ "_$(./tools/removed $id)" = "_1" ]
  then
    echo $ln
    echo "# $ln" >> $1.tmp
    cx = `expr $cx + 1`
  else
    echo $ln >> $1.tmp
  fi
done < $1

mv $1.tmp $1

echo "$cx lines are commented out"
